import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarComponent } from "@/components/SidebarComponent";
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Decarbond",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          `flex w-screen min-h-screen bg-neutral-100 dark:bg-neutral-800 text-black`
        )}
      >
        <SidebarComponent />
        {children}
      </body>
    </html>
  );
}
